source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'RegexKitLite-NoWarning', '1.1.0'
pod 'TPKeyboardAvoiding', '1.2.4'
pod 'BlocksKit', '2.2.5'
pod 'ReactiveCocoa', '2.3.1'
pod 'Masonry', '0.5.3'
pod 'MBProgressHUD', '0.9'
pod 'TPKeyboardAvoiding', '1.2.4'
